
services:
  test_hh_124422381_front:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "5173:5173"
    networks:
      - test_hh_net_124422381
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"


networks:
  test_hh_net_124422381:
    external: true
