
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
    ports:
      - "8080:8080"       # панель управления
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - test_hh_net_124422381

networks:
  test_hh_net_124422381:
    external: true
